name: gidi_ride_driver
description: Driver app for gidi ride

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_auth: ^0.6.6
  image_picker: ^0.4.6
  shared_preferences: ^0.4.2
  modal_progress_hud: ^0.1.0
  firebase_storage: ^1.0.4
  location: ^1.4.1
  firebase_database: ^1.0.5
  firebase_core: any
  #carousel_pro: ^0.0.13
  carousel_slider: ^1.1.0
  datetime_picker_formfield: ^0.1.3
  fluttertoast: ^2.0.7
  url_launcher: ^3.0.3
  firebase_messaging: ^2.1.0
  android_alarm_manager: ^0.4.1+3
  http: ^0.12.0
  flutter_paystack: ^0.9.3
  #document_chooser: ^0.0.2
  flutter_rating: ^0.0.2
  progress_hud_v2: ^2.0.0
  device_info: ^0.3.0
  common_utils: ^1.0.9
  flutter_countdown: ^0.1.4
  #google_maps_flutter: ^0.3.0+2
  google_maps_flutter:
    git:
      url: git://github.com/jan1za/plugins
      path: packages/google_maps_flutter
  #bidirectional_scroll_view: ^0.0.6
  #esys_flutter_share: ^0.0.5
  flutter_google_places: ^0.1.4+1
  zendesk: ^0.0.1
  scrollable_bottom_sheet: ^0.0.4
  #share_extend: ^1.0.3
  #map_view: ^0.0.14
  #fcm_push: ^1.3.1
  flutter_datetime_picker: ^1.0.6
  #rapido: ^0.1.7
  screen: ^0.0.4


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - sus_middle.png
   - sus_top.png
   - sus_bottom.png
   - header_logo.png
   - terms.png
   - welcome.png
   - user_dp.png
   - trips.png
   - payment.png
   - legal.png
   - help.png
   - free_rides.png
   - settings.png
   - cash.png
   - invites.png
   - rec.png
   - gidicar.png
   - gidibike.png
   - map_car.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
   - family: Lato
     fonts:
      - asset: fonts/Lato-Black.ttf
      - asset: fonts/Lato-Light.ttf
      - asset: fonts/Lato-Medium.ttf
      - asset: fonts/Lato-Regular.ttf
      - asset: fonts/Lato-Thin.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
